version: '3'

services:
  lavalink:
    image: fredboat/lavalink:master-v3
    volumes:
      - ./lavalink/application.yml:/opt/Lavalink/application.yml
    ports:
    - 2333
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:2333"]
        interval: 30s
        timeout: 10s
        retries: 5
    networks:
      - common-shared-network

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/bot:ro
    tty: true
    depends_on:
      - lavalink
    links: 
      - lavalink
    environment:
      LAVALINK_HOST: lavalink
      LAVALINK_PORT: 2333
      LAVALINK_PASSWORD: youshallnotpass
    restart: on-failure
    env_file:
      - .env
    networks:
      - common-shared-network

networks:
  common-shared-network: