version: '3'

services:
  lavalink:
    image: fredboat/lavalink:master-v3
    restart: always
    volumes:
      - ./lavalink.yml:/opt/Lavalink/application.yml
      - ./lavalink_logs:/opt/Lavalink/logs
    ports:
    - 2333:2333
    entrypoint: java -Xmx128m -jar Lavalink.jar
    networks:
      - common-shared-network

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/bot:ro
    tty: true
    depends_on:
      - lavalink
    environment:
      LAVALINK_HOST: lavalink
      LAVALINK_PORT: 2333
      LAVALINK_PASSWORD: youshallnotpass
    restart: on-failure
    env_file:
      - .env
    networks:
      - common-shared-network

networks:
  common-shared-network: